name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Cache butterfly theme
        uses: actions/cache@v2
        with:
          path: themes
          key: ${{ runner.OS }}-butterfly-cache
          restore-keys: |
            ${{ runner.OS }}-butterfly-cache
      - name: Install Dependencies
        run: npm install
      - name: Install Butterfly theme
        run : "[[ ! -d themes/butterfly ]] && git clone -b master https://github.com/jerryc127/hexo-theme-butterfly.git themes/butterfly"
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
